
package uk.ac.rhul.cs.calculatorwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorServerImplService", targetNamespace = "http://calculatorwebservice.cs.rhul.ac.uk/", wsdlLocation = "http://localhost:31007/WS/CalculatorServer?wsdl")
public class CalculatorServerImplService
    extends Service
{

    private final static URL CALCULATORSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORSERVERIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATORSERVERIMPLSERVICE_QNAME = new QName("http://calculatorwebservice.cs.rhul.ac.uk/", "CalculatorServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:31007/WS/CalculatorServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSERVERIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATORSERVERIMPLSERVICE_EXCEPTION = e;
    }

    public CalculatorServerImplService() {
        super(__getWsdlLocation(), CALCULATORSERVERIMPLSERVICE_QNAME);
    }

    public CalculatorServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSERVERIMPLSERVICE_QNAME, features);
    }

    public CalculatorServerImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSERVERIMPLSERVICE_QNAME);
    }

    public CalculatorServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSERVERIMPLSERVICE_QNAME, features);
    }

    public CalculatorServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorServer
     */
    @WebEndpoint(name = "CalculatorServerImplPort")
    public CalculatorServer getCalculatorServerImplPort() {
        return super.getPort(new QName("http://calculatorwebservice.cs.rhul.ac.uk/", "CalculatorServerImplPort"), CalculatorServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorServer
     */
    @WebEndpoint(name = "CalculatorServerImplPort")
    public CalculatorServer getCalculatorServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calculatorwebservice.cs.rhul.ac.uk/", "CalculatorServerImplPort"), CalculatorServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATORSERVERIMPLSERVICE_EXCEPTION;
        }
        return CALCULATORSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
