
package uk.ac.rhul.cs.calculatorwebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorServer", targetNamespace = "http://calculatorwebservice.cs.rhul.ac.uk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorServer {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calc", targetNamespace = "http://calculatorwebservice.cs.rhul.ac.uk/", className = "uk.ac.rhul.cs.calculatorwebservice.Calc")
    @ResponseWrapper(localName = "calcResponse", targetNamespace = "http://calculatorwebservice.cs.rhul.ac.uk/", className = "uk.ac.rhul.cs.calculatorwebservice.CalcResponse")
    @Action(input = "http://calculatorwebservice.cs.rhul.ac.uk/CalculatorServer/calcRequest", output = "http://calculatorwebservice.cs.rhul.ac.uk/CalculatorServer/calcResponse")
    public String calc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
